version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=medlife
      - MONGO_INITDB_ROOT_PASSWORD=6ZCEfxeDB
      - MONGO_INITDB_DATABASE=medlife
    networks:
      - medlife-network
  nodeapp:
    container_name: medlife
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3004:3004"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - medlife-network
    stdin_open: true
    tty: true
networks:
  medlife-network:
    driver: bridge