export { default as UserController } from "./UserController";
export { default as DoctorController } from "./DoctorController";
export { default as ServicesGroupController } from "./ServicesGroupController";
export { default as ServiceController } from "./ServiceController";
export { default as NewsController } from "./NewsController";
export { default as CommentController } from "./CommentController";
export { default as GalleryController } from "./GalleryController";
export { default as CallRequestController } from "./CallRequestController";
export { default as AppointmentController } from "./AppointmentController";
